version: '3'
services:
    db:
      image: mysql:latest
      container_name: "db"
      restart: always
      volumes:
        - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
        - db-data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "db_linkurto"
          MYSQL_USER: "admin"
          MYSQL_PASSWORD: "senha321"
      ports:
          - "3306:3306"
      networks:
        - linkurto-net 
      healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10

    linkurto:
      container_name: linkurto
      image: G4bzz/linkurto:1.0.0
      ports:
        - "8088:8088"
      networks:
        - linkurto-net
      depends_on:
        db:
          condition: service_healthy

    prometheus:
      image: prom/prometheus:v2.53.5
      container_name: prometheus
      volumes:
        - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"
      ports:
        - "9090:9090"
      networks:
        - linkurto-net 

    grafana:
      image: grafana/grafana:12.0.2
      container_name: grafana
      ports:
        - "3000:3000"
      networks:
        - linkurto-net 
networks:
  linkurto-net:
    driver: bridge

volumes:
  db-data: