version: '3'
services:
    db:
       image: mysql:latest
       container_name: "db"
       restart: always
       volumes:
         - db-data:/var/lib/mysql
       environment:
           MYSQL_ROOT_PASSWORD: "root"
           MYSQL_DATABASE: "db_linkurto"
           MYSQL_USER: "admin"
           MYSQL_PASSWORD: "senha321"
       ports:
           - "3306:3306"

    prometheus:
        image: prom/prometheus:v2.53.5
        container_name: prometheus
        volumes:
          - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
        command:
          - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
          - "9090:9090"
volumes:
  db-data: